// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJJG5Hjqn-ar8H0quig00m6x7tsAijduQ',
    appId: '1:444182678264:web:c2e54932aa11507fa3890d',
    messagingSenderId: '444182678264',
    projectId: 'loged-bdcc6',
    authDomain: 'loged-bdcc6.firebaseapp.com',
    storageBucket: 'loged-bdcc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWiGmfMoGLQdpqao_hKbtNr96gbOTT5g0',
    appId: '1:444182678264:android:70457762bfcec410a3890d',
    messagingSenderId: '444182678264',
    projectId: 'loged-bdcc6',
    storageBucket: 'loged-bdcc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXZL35Ztc1Z-TuHoXAYRHZc5BIlIdtgts',
    appId: '1:444182678264:ios:b79f02eac02ed86ca3890d',
    messagingSenderId: '444182678264',
    projectId: 'loged-bdcc6',
    storageBucket: 'loged-bdcc6.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXZL35Ztc1Z-TuHoXAYRHZc5BIlIdtgts',
    appId: '1:444182678264:ios:f9c1713f60116b47a3890d',
    messagingSenderId: '444182678264',
    projectId: 'loged-bdcc6',
    storageBucket: 'loged-bdcc6.appspot.com',
    iosBundleId: 'com.example.signin.RunnerTests',
  );
}
